- name: Delete default nginx configurations
  file:
    path=/etc/nginx/conf.d/{{ item }}
    state=absent
  with_items:
   - default.conf
   - example_ssl.conf

- name: Create nginx virtual host for Kibana
  template:
    src=kibana.conf.j2
    dest=/etc/nginx/conf.d/kibana.conf
    owner=root
    group=root
    mode=0644
  notify:
   - restart nginx

- name: Restart nginx service
  service:
    name=nginx
    state=restarted
